site_name: numerblox
theme:
  name: material
  palette:
    primary: black
    accent: cyan
  font:
    text: Roboto
  custom_dir: docs/assets
  icon:
    logo: cc_white
  favicon: assets/images/favicon.ico
  features:
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - content.code.copy

nav:
  - Home: index.md
  - End-To-End Examples: end_to_end.md
  
  - Downloaders: download.md
  - NumerFrame: numerframe.md
  - Preprocessing: preprocessing.md
  - Target Engineering: targets.md
  - Postprocessing: postprocessing.md
  - Meta Pipelines: meta.md
  - Prediction Loaders: prediction_loaders.md
  - Models: models.md
  - Evaluation: evaluation.md
  - Submitters: submission.md

  - How To Contribute: contributing.md
  - About CrowdCent: crowdcent.md
  - Disclaimer: disclaimer.md
  - API Reference: api.md

plugins:
  - mkdocstrings