# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://crowdcent.github.io/numerai-blocks/"

git_url = "https://github.com/crowdcent/numerai-blocks/tree/main/"

def custom_doc_links(name): return None
