name: UV CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install -e ".[test]"

      - name: Run tests
        run: |
          uv run -- pytest

      - name: Build wheel
        run: |
          uv pip install build
          uv run -- python -m build --wheel

      - name: Install built wheel
        run: |
          uv pip install dist/*.whl

      - name: Run tests with coverage
        run: |
          uv pip install pytest-cov
          uv run -- pytest -s tests/ --cov=numerblox --cov-report term-missing
