# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Check": "00_download.ipynb"}

modules = ["download.py"]

doc_url = "https://crowdcent.github.io/numerai_blocks/"

git_url = "https://github.com/crowdcent/numerai_blocks/tree/main/"

def custom_doc_links(name): return None
