# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BaseIO": "00_download.ipynb",
         "BaseDownloader": "00_download.ipynb",
         "NumeraiClassicDownloader": "00_download.ipynb",
         "Dataset": "02_dataset.ipynb",
         "BaseProcessor": "03_preprocessing.ipynb",
         "support_dataf_processing": "03_preprocessing.ipynb",
         "support_dataset_processing": "03_preprocessing.ipynb",
         "display_processor_info": "03_preprocessing.ipynb",
         "CopyPreProcessor": "03_preprocessing.ipynb",
         "GroupStatsPreProcessor": "03_preprocessing.ipynb",
         "Key": "08_key.ipynb",
         "load_key_from_json": "08_key.ipynb",
         "BaseSubmittor": "09_submission.ipynb",
         "NumeraiClassicSubmittor": "09_submission.ipynb",
         "NumeraiSignalsSubmittor": "09_submission.ipynb"}

modules = ["download.py",
           "dataset.py",
           "preprocessing.py",
           "key.py",
           "submission.py"]

doc_url = "https://crowdcent.github.io/numerai_blocks/"

git_url = "https://github.com/crowdcent/numerai_blocks/tree/main/"

def custom_doc_links(name): return None
