# AUTOGENERATED! DO NOT EDIT! File to edit: dev_nbs/00_download.ipynb (unless otherwise specified).

__all__ = ['Check']

# Cell
class Check:
    """ Check to test if NBDev syncs properly """
    def __init__(self, one=1):
        self.one = one
