# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/08_key.ipynb (unless otherwise specified).

__all__ = ['Key', 'load_key_from_json']

# Cell
import json
import base64
from dataclasses import dataclass, FrozenInstanceError
from rich import print as rich_print

# Cell
@dataclass(frozen=True)
class Key:
    """ Immutable and validated Numerai credentials. """
    pub_id: str = ""
    secret_key: str = ""
    # Decode credentials
    pub_id = base64.b64decode(pub_id, validate=True).decode('utf-8')
    secret_key = base64.b64decode(secret_key, validate=True).decode('utf-8')

    def __post_init__(self):
        rich_print(f":key: Intialized {self.__repr__()} :key:")

    def __repr__(self):
        return f"Numerai Authentication Key. pub_id: '{pub_id}'"

    def __str__(self):
        return self.__repr__()

def load_key_from_json(file_path: str, *args, **kwargs):
    """
    Initialize Key object from JSON file.
    Credentials file should have the following format:
    {
    "pub_id": "PUBLIC_ID",
    "secret_key": "SECRET_KEY"
    }
    """
    with open(file_path) as json_file:
        json_data = json.load(json_file, *args, **kwargs)
    pub_id = json_data['pub_id']
    secret_key = json_data['secret_key']
    return Key(pub_id=pub_id, secret_key=secret_key)